name: "✨ Feature Request"
description: "Suggest an idea for this project "
title: "✨ Feat:"
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: "Describe the feature"
      description:
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Add ScreenShots"
      description: "Add a Screenshot to explain your feature better"
    validations:
      required: false